# Generated by Django 4.0.1 on 2022-02-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pagina_Lenceria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('precio_compra', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('talle', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Pagina_Lenceria.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Pagina_Lenceria.cliente')),
            ],
        ),
    ]
