# Generated by Django 4.0.1 on 2022-02-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pagina_Lenceria', '0002_cliente_productor_producto_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
